fix: convert compressed key
xiboXD/BIP39Wallet-NBitcoin pull request #8
Opened 2023-09-26 10:34 UTC by xibo1

2023-09-27 02:09 UTC, zhifenglee-portkey commented on src/PrivateKey.cs
>              var signature = _bitcoinKey.SignCompact(hash32, false);
The if statement should be operating on the private key first before SignCompact.

if(compressed)
> OperateOnPrivateKey
SignCompact

2023-09-28 12:16 UTC, gldeng commented on src/PrivateKey.cs
> +                    return new BitcoinKey(keyBytes, -1, false);
Assign the value to _bitcoinKey

2023-09-28 12:16 UTC, gldeng commented on test/BIP39Wallet.Tests.cs
> +        public void Sign_WithCompressedKeyAndDecompressedKey()
Split the test case into two.

2023-09-29 02:16 UTC, xibo1 commented on src/PrivateKey.cs
> +                    return new BitcoinKey(keyBytes, -1, false);
done

2023-09-29 02:16 UTC, xibo1 commented on test/BIP39Wallet.Tests.cs
> +        public void Sign_WithCompressedKeyAndDecompressedKey()
done

2023-09-29 03:10 UTC, gldeng requested changes

2023-09-29 03:10 UTC, gldeng commented on src/PrivateKey.cs
> +                    return _bitcoinKey = new BitcoinKey(keyBytes, -1, false);
```suggestion
                    _bitcoinKey = new BitcoinKey(keyBytes, -1, false);
```

2023-10-02 08:22 UTC, closed without merging